<?php

namespace AppBundle\Repository;

/**
 * TrainersRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TrainersRepository extends \Doctrine\ORM\EntityRepository
{
}
